spring:
  security:
    oauth2:
      client:
        # registration
        registration:
          google:
            client-id: 769697044882-n1busm7e191uqatrikvhon9pl7h84eob.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: profile,email
          kakao:
            client-id: 731837ca3b4c02f205c027eea42a9b07
            client-secert: veQtNWDU6CsV1e3dWkpYPFw9TPlpXeAV
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile,account_email
            client-name: kakao
            client-authentication-method: POST
          naver:
            client-id: vJqnNtOUtl_zCbyPHoGw
            client-secret: Gcs1bXJsQW
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email.profile_image
            client-name: Naver
          facebook:
            client-id: 500275384288471
            client-secret: 05b58132fec721b03b1fc6f3a386cd04
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email, public_profile
        # provider #
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          facebook:
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
